pub const FRONTEND_CACHE_NAMESPACE: &str = "frontend";
pub const FRONTEND_ARTIFACT_SCHEMA_VERSION: u32 = 3;

#[derive(
    Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, serde::Serialize, serde::Deserialize,
)]
pub enum FrontendArtifactKind {
    SourceSet,
    ParsedSource,
    ParsedSourceSet,
    ArtifactManifest,
    SourceFingerprintSummary,
    ModuleImportExportSummary,
    ArtifactDependencySummary,
    ArtifactReuseStats,
    ModuleIndex,
    UnitTree,
    ImportGraph,
    ModuleTopoOrder,
    AffectedModuleSet,
    HirModule,
    HirBody,
    HirProgram,
    ResolvedImports,
    ResolvedPaths,
    SignatureFacts,
    TopLevelLetFacts,
    TypeFacts,
    EffectPipelineArtifacts,
    EffectFacts,
    BodyArtifactReuseIndex,
    Diagnostics,
    ProjectEntry,
    ReachabilityFacts,
    CheckedProject,
}

impl FrontendArtifactKind {
    pub fn key(self) -> &'static str {
        match self {
            Self::SourceSet => "source_set",
            Self::ParsedSource => "parsed_source",
            Self::ParsedSourceSet => "parsed_source_set",
            Self::ArtifactManifest => "artifact_manifest",
            Self::SourceFingerprintSummary => "source_fingerprint_summary",
            Self::ModuleImportExportSummary => "module_import_export_summary",
            Self::ArtifactDependencySummary => "artifact_dependency_summary",
            Self::ArtifactReuseStats => "artifact_reuse_stats",
            Self::ModuleIndex => "module_index",
            Self::UnitTree => "unit_tree",
            Self::ImportGraph => "import_graph",
            Self::ModuleTopoOrder => "module_topo_order",
            Self::AffectedModuleSet => "affected_module_set",
            Self::HirModule => "hir_module",
            Self::HirBody => "hir_body",
            Self::HirProgram => "hir_program",
            Self::ResolvedImports => "resolved_imports",
            Self::ResolvedPaths => "resolved_paths",
            Self::SignatureFacts => "signature_facts",
            Self::TopLevelLetFacts => "top_level_let_facts",
            Self::TypeFacts => "type_facts",
            Self::EffectPipelineArtifacts => "effect_pipeline_artifacts",
            Self::EffectFacts => "effect_facts",
            Self::BodyArtifactReuseIndex => "body_artifact_reuse_index",
            Self::Diagnostics => "diagnostics",
            Self::ProjectEntry => "project_entry",
            Self::ReachabilityFacts => "reachability_facts",
            Self::CheckedProject => "checked_project",
        }
    }

    pub fn from_key(key: &str) -> Option<Self> {
        Some(match key {
            "source_set" => Self::SourceSet,
            "parsed_source" => Self::ParsedSource,
            "parsed_source_set" => Self::ParsedSourceSet,
            "artifact_manifest" => Self::ArtifactManifest,
            "source_fingerprint_summary" => Self::SourceFingerprintSummary,
            "module_import_export_summary" => Self::ModuleImportExportSummary,
            "artifact_dependency_summary" => Self::ArtifactDependencySummary,
            "artifact_reuse_stats" => Self::ArtifactReuseStats,
            "module_index" => Self::ModuleIndex,
            "unit_tree" => Self::UnitTree,
            "import_graph" => Self::ImportGraph,
            "module_topo_order" => Self::ModuleTopoOrder,
            "affected_module_set" => Self::AffectedModuleSet,
            "hir_module" => Self::HirModule,
            "hir_body" => Self::HirBody,
            "hir_program" => Self::HirProgram,
            "resolved_imports" => Self::ResolvedImports,
            "resolved_paths" => Self::ResolvedPaths,
            "signature_facts" => Self::SignatureFacts,
            "top_level_let_facts" => Self::TopLevelLetFacts,
            "type_facts" => Self::TypeFacts,
            "effect_pipeline_artifacts" => Self::EffectPipelineArtifacts,
            "effect_facts" => Self::EffectFacts,
            "body_artifact_reuse_index" => Self::BodyArtifactReuseIndex,
            "diagnostics" => Self::Diagnostics,
            "project_entry" => Self::ProjectEntry,
            "reachability_facts" => Self::ReachabilityFacts,
            "checked_project" => Self::CheckedProject,
            _ => return None,
        })
    }
}
