[package]
name = "etas_effects"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
etas_core.workspace = true
etas_hir.workspace = true
etas_hir_analysis.workspace = true
etas_std.workspace = true
etas_types.workspace = true
etas_utils.workspace = true
serde.workspace = true

[dev-dependencies]
etas_syntax.workspace = true
